"""
Provider-agnostic abstract base classes for all pipeline stage adapters.

Defines the contracts that every STT, LLM, TTS, and Avatar adapter must
implement. Concrete adapters (Deepgram, Groq, Cartesia, Simli, etc.) inherit
from these ABCs and provide the actual integration logic.

No provider-specific imports or logic belong in this file.

Pipeline stage: Infrastructure (shared by all stages)

Exports:
    BaseSTTAdapter    -- Speech-to-text adapter interface
    BaseLLMEngine     -- Large language model engine interface
    BaseTTSAdapter    -- Text-to-speech adapter interface
    BaseAvatarAdapter -- Video avatar renderer interface
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import AsyncIterator

from pipeline.errors import AdapterError, AdapterTimeoutError  # noqa: F401


class BaseSTTAdapter(ABC):
    """Abstract base class for speech-to-text adapters.

    Concrete implementations consume a stream of raw audio frames and
    produce a final transcript string. They must also support cooperative
    cancellation so the orchestrator can abort an in-progress recognition
    when a student interrupt is detected.
    """

    @abstractmethod
    async def transcribe(
        self,
        audio_frames: AsyncIterator[bytes],
        metrics: "MetricsCollector",
    ) -> str:
        """Consume an audio stream and return the final transcript.

        Reads audio frames until the stream is exhausted or an
        end-of-utterance signal is detected, then returns the full
        transcription text.

        Args:
            audio_frames: Async iterator yielding raw audio chunks
                          (PCM 16-bit, 16 kHz mono expected by most
                          providers).
            metrics:      MetricsCollector instance for recording
                          per-stage latency (time-to-first-result,
                          total duration).

        Returns:
            The transcribed text from the audio stream.

        Raises:
            AdapterError:        The underlying STT service returned an
                                 error or the connection failed.
            AdapterTimeoutError: The transcription exceeded its latency
                                 budget (stt_max_ms).
        """
        ...

    @abstractmethod
    async def cancel(self) -> None:
        """Cancel any in-progress transcription.

        Called by the orchestrator when a student interrupt is detected
        and the current STT pass must be abandoned. Implementations
        should release network resources and abort pending requests.

        This method must be safe to call even if no transcription is
        currently active (idempotent).
        """
        ...


class BaseLLMEngine(ABC):
    """Abstract base class for large language model engines.

    Concrete implementations stream Socratic tutor responses token by
    token, and also provide a non-streaming helper for quick one-shot
    calls (e.g. topic classification, safety checks).
    """

    @abstractmethod
    async def stream(
        self,
        transcript: str,
        context: list[dict],
        metrics: "MetricsCollector",
    ) -> AsyncIterator[str]:
        """Stream LLM response tokens for a student utterance.

        Sends the student transcript along with conversation history
        to the model and yields response tokens as they arrive.
        The first yielded token marks time-to-first-token (TTFT)
        for latency measurement.

        Args:
            transcript: The student's transcribed utterance.
            context:    Conversation history as a list of message dicts,
                        each with 'role' and 'content' keys. Follows
                        the OpenAI chat-completions format.
            metrics:    MetricsCollector instance for recording TTFT
                        and total generation time.

        Yields:
            str: Individual response tokens (or small token groups)
                 as they are generated by the model.

        Raises:
            AdapterError:        The LLM service returned an error,
                                 the connection dropped, or the
                                 response was malformed.
            AdapterTimeoutError: Time-to-first-token or total generation
                                 time exceeded the latency budget.
        """
        ...

    @abstractmethod
    async def quick_call(self, prompt: str, model: str) -> str:
        """Make a non-streaming, single-turn LLM call.

        Useful for lightweight tasks that do not need token streaming:
        topic classification, safety filtering, or summary generation.

        Args:
            prompt: The complete prompt to send to the model.
            model:  The model identifier to use for this call
                    (e.g. "llama-3.3-70b-versatile").

        Returns:
            The full model response as a single string.

        Raises:
            AdapterError: The LLM service returned an error or the
                          connection failed.
        """
        ...

    @abstractmethod
    async def cancel(self) -> None:
        """Cancel any in-progress LLM generation.

        Called by the orchestrator when a student interrupt is detected
        and the current response stream must be abandoned.
        Implementations should abort pending API requests and release
        resources.

        This method must be safe to call even if no generation is
        currently active (idempotent).
        """
        ...


class BaseTTSAdapter(ABC):
    """Abstract base class for text-to-speech adapters.

    Concrete implementations consume a sentence of text and yield
    audio chunks suitable for piping into the avatar renderer.
    Streaming is required for low-latency playback.
    """

    @abstractmethod
    async def stream(
        self,
        sentence: str,
        metrics: "MetricsCollector",
    ) -> AsyncIterator[bytes]:
        """Stream synthesised audio for a single sentence.

        Sends the text to the TTS provider and yields audio chunks
        as they become available. The first yielded chunk marks
        time-to-first-audio-byte for latency measurement.

        Args:
            sentence: The text to synthesise into speech. Typically
                      a single sentence extracted by the sentence
                      buffer from the LLM token stream.
            metrics:  MetricsCollector instance for recording
                      time-to-first-byte and total synthesis time.

        Yields:
            bytes: Raw audio chunks (format depends on provider;
                   commonly PCM 16-bit 24 kHz or Opus-encoded).

        Raises:
            AdapterError:        The TTS service returned an error
                                 or the connection failed.
            AdapterTimeoutError: Audio synthesis exceeded its latency
                                 budget (tts_max_ms).
        """
        ...

    @abstractmethod
    async def cancel(self) -> None:
        """Cancel any in-progress speech synthesis.

        Called by the orchestrator when a student interrupt is detected
        and the current TTS pass must be abandoned. Implementations
        should abort pending API requests, flush internal buffers,
        and release resources.

        This method must be safe to call even if no synthesis is
        currently active (idempotent).
        """
        ...


class BaseAvatarAdapter(ABC):
    """Abstract base class for video avatar rendering adapters.

    Concrete implementations receive a stream of audio chunks and
    drive a lip-synced video avatar in real time. They must also
    support returning the avatar to its listening (idle) pose when
    an interrupt occurs.
    """

    @abstractmethod
    async def stream_audio(
        self,
        audio_chunks: AsyncIterator[bytes],
        metrics: "MetricsCollector",
    ) -> None:
        """Feed audio to the avatar for real-time lip-synced rendering.

        Consumes audio chunks produced by the TTS adapter and sends
        them to the avatar rendering backend. The avatar should begin
        speaking (lip-syncing) as soon as the first chunk arrives.

        Args:
            audio_chunks: Async iterator yielding raw audio chunks
                          from the TTS stage.
            metrics:      MetricsCollector instance for recording
                          rendering latency and frame timing.

        Raises:
            AdapterError:        The avatar service returned an error
                                 or the rendering connection failed.
            AdapterTimeoutError: Rendering latency exceeded the
                                 per-stage budget (avatar_max_ms).
        """
        ...

    @abstractmethod
    async def stop(self) -> None:
        """Stop speaking and return the avatar to its listening pose.

        Called by the orchestrator during interrupt handling so the
        avatar visually transitions back to an attentive idle state.
        Implementations should immediately cease lip-sync playback
        and send the appropriate idle/listening signal to the renderer.

        This method must be safe to call even if the avatar is already
        idle (idempotent).
        """
        ...
